### ISSUE TITLE
Build issues on nightly

### ISSUE THREAD

**Issue by palfrey** [avito-tech/bioyino#65]
https://github.com/palfrey/bioyino/runs/3273000488?check_suite_focus=true running `rustc 1.56.0-nightly (574d37568 2021-08-07)`

```
error: internal compiler error: unexpected concrete region in borrowck: ReEarlyBound(0, 'a)
Error:    --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/bioyino-metric-0.3.1/src/parser.rs:48:1
    |
48  | / pub fn metric_stream_parser<'a, I, F>(max_unparsed: usize, max_tags_len: usize) -> impl Parser<I, Output = ParsedPart<F>, PartialState = ...
49  | | where
50  | |     I: 'a + combine::StreamOnce<Token = u8, Range = &'a [u8], Position = PointerOffset<[u8]>> + std::fmt::Debug + RangeStream,
51  | |     I::Error: ParseError<I::Token, I::Range, I::Position>,
...   |
150 | |     ))
151 | | }
    | |_^
    |
    = note: delayed at compiler/rustc_mir/src/borrow_check/region_infer/opaque_types.rs:88:44

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1065:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I think this is https://github.com/rust-lang/rust/issues/83190 and I've added a note about this there

**Comment by Albibek** [comment]
Since we aim at stable Rust, we don't expect bioyino to compile on any nightly version.
